### ISSUE TITLE
Grab predict unable to distinguish heavy vs lite balloon configs

### ISSUE THREAD

**Issue by TheKoola** [TheKoola/eosstracker#3]
https://github.com/TheKoola/eosstracker/blob/8f429a112f457f471661fd0c3cac06e9a7fd8ebb/www/grabprediction.php#L292

By grabbing the numeric designator only and using it to form the URL for the prediction file, grabprediction.php has no way of knowing if it is heavy EOSS-303 (maps to 303 prediction) or lite EOSSL-303 (should map to 703 prediction).  Would need some other way to identify lite balloon configurations.

**Comment by Deatojef** [comment]
Excellent point (and sorry for the 6-month delay in replying).  If the normal procedure is to name flights based on EOSSx-yyy AND lite predictions are identified by the “7” in EOSSx-7yy, then we could change the flight suffix search to look for 7xx instead of xxx for those flights with a lite designation (ex. EOSSL-yyy).
